# Generated by Django 4.1.1 on 2022-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Empty Room', max_length=100),
            preserve_default=False,
        ),
    ]
